name: skripsi_ba_parkir
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  cloud_firestore: 4.12.2
  convex_bottom_bar: 3.2.0
  cupertino_icons: ^1.0.2
  dotted_border: ^2.1.0
  firebase_auth: 4.12.1
  firebase_core: 2.21.0
  firebase_storage: 11.4.1
  flutter:
    sdk: flutter
  flutter_barcode_scanner: 2.0.0
  flutter_launcher_icons: ^0.13.1
  geocoding: 2.1.1
  geolocator: 10.1.0
  get: 4.6.6
  http: ^1.1.0
  image_picker: 1.0.4
  intl: 0.18.1
  lottie: ^2.7.0
  qr_flutter: 4.1.0
  quiver: 3.2.1
  rxdart: ^0.27.7
  syncfusion_flutter_datepicker: 23.1.43
  url_launcher: ^6.2.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/lotties/
    - assets/logo/
    - assets/img/
    - assets/bg/
