// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO8cBplA4yncoALPfPbtApl1NB3upLh48',
    appId: '1:370748406251:web:bbcca710ba12e3d03441ae',
    messagingSenderId: '370748406251',
    projectId: 'skripsi-ba-parkir-99',
    authDomain: 'skripsi-ba-parkir-99.firebaseapp.com',
    storageBucket: 'skripsi-ba-parkir-99.appspot.com',
    measurementId: 'G-1738KDN1FC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEe6-IHbDhWBBEKiMOCQkEU2DmsZ4Hwy4',
    appId: '1:370748406251:android:a83e916bb422e86c3441ae',
    messagingSenderId: '370748406251',
    projectId: 'skripsi-ba-parkir-99',
    storageBucket: 'skripsi-ba-parkir-99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr0mvVXn92nuI-VbnVgD47g88LgPtAp_Q',
    appId: '1:370748406251:ios:aadaf74b1f95787f3441ae',
    messagingSenderId: '370748406251',
    projectId: 'skripsi-ba-parkir-99',
    storageBucket: 'skripsi-ba-parkir-99.appspot.com',
    iosBundleId: 'com.ramaproject.skripsiBaParkir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr0mvVXn92nuI-VbnVgD47g88LgPtAp_Q',
    appId: '1:370748406251:ios:5c0008dfc8093b863441ae',
    messagingSenderId: '370748406251',
    projectId: 'skripsi-ba-parkir-99',
    storageBucket: 'skripsi-ba-parkir-99.appspot.com',
    iosBundleId: 'com.ramaproject.skripsiBaParkir.RunnerTests',
  );
}
